"""Render a review dict as PR-comment-ready markdown (W7).

Pure formatting, no LLM calls. Findings are grouped by severity; dropped
findings go into a collapsed <details> block so the audit trail travels
with the comment without drowning it.
"""

_SEV_ORDER = {"high": 0, "medium": 1, "low": 2}
_SEV_BADGE = {"high": "🔴 high", "medium": "🟡 medium", "low": "🔵 low"}


def _finding_lines(f: dict) -> list[str]:
    badge = _SEV_BADGE.get(f.get("severity"), f.get("severity", "?"))
    out = [f"- **{badge}** `{f['file']}:{f['line']}` — {f['issue'].strip()}"]
    suggestion = f.get("suggestion", "").strip()
    if suggestion:
        out.append(f"  - 💡 {suggestion}")
    return out


def render_markdown(review: dict, title: str = "Code review") -> str:
    ranked = sorted(review.get("findings", []),
                    key=lambda f: _SEV_ORDER.get(f.get("severity"), 3))
    findings = [f for f in ranked if f.get("verification") != "uncertain"]
    uncertain = [f for f in ranked if f.get("verification") == "uncertain"]
    dropped = review.get("dropped_findings", [])

    lines = [f"## 🤖 {title}", "", review.get("summary", "").strip(), ""]
    if findings:
        lines.append(f"### Findings ({len(findings)})")
        lines.append("")
        for f in findings:
            lines.extend(_finding_lines(f))
        lines.append("")
    elif not uncertain:
        lines += ["**No findings survived verification.** ✅", ""]

    if uncertain:
        lines.append(f"### ⚠️ Unverified findings ({len(uncertain)}) — "
                     "the two verification passes disagreed")
        lines.append("")
        for f in uncertain:
            lines.extend(_finding_lines(f))
            dissent = f.get("dissent_reason", "").strip()
            if dissent:
                lines.append(f"  - 🗳️ dissenting verdict: {dissent}")
        lines.append("")

    if dropped:
        lines.append("<details>")
        lines.append(f"<summary>🗑️ {len(dropped)} candidate finding(s) dropped by the "
                     "verifier (click to audit)</summary>")
        lines.append("")
        for f in dropped:
            lines.append(f"- `{f['file']}:{f['line']}` {f['issue'].strip()}")
            lines.append(f"  - drop reason: {f.get('drop_reason', '').strip()}")
        lines += ["", "</details>", ""]

    lines.append("*Generated by code-review-agent; findings verified by a "
                 "second-pass verifier with repo tools.*")
    return "\n".join(lines) + "\n"
