"""GitHub PR review payloads from a review dict (W17 B3, dry-run scope).

Pure functions: parse the unified diff into commentable (file, line)
positions, snap findings onto them (GitHub inline comments must target a
line that appears in the diff), and build the
POST /repos/{owner}/{repo}/pulls/{n}/reviews payload. Findings that
cannot be placed inline degrade into the review body instead of being
lost. Live posting is wired in agent.py behind --post; --post-dry-run
prints the gh command and payload without executing (this repo has no
GitHub remote, so live posting is deliberately unvalidated -- see
docs/examples/review.yml for the CI template).
"""
import json
import re

_HUNK_RE = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@")
_SEV_BADGE = {"high": "🔴 high", "medium": "🟡 medium", "low": "🔵 low"}
SNAP_TOL = 5   # max distance a finding may be moved to a commentable line


def commentable_lines(diff_text: str) -> dict:
    """{new-file path: set of new-side line numbers shown in the diff}.
    Added and context lines are commentable (side RIGHT); removed lines
    are not (they only exist on the old side)."""
    files: dict = {}
    current = None
    new_ln = None
    for line in diff_text.splitlines():
        if line.startswith("+++ "):
            name = line[4:].split("\t")[0].strip()
            if name.startswith("b/"):
                name = name[2:]
            current = None if name == "/dev/null" else name
            new_ln = None
            continue
        if line.startswith(("diff ", "--- ", "index ")):
            new_ln = None
            continue
        m = _HUNK_RE.match(line)
        if m is not None:
            new_ln = int(m.group(1)) if current else None
            continue
        if current is None or new_ln is None:
            continue
        if line.startswith("+"):
            files.setdefault(current, set()).add(new_ln)
            new_ln += 1
        elif line.startswith("-") or line.startswith("\\"):
            pass                       # old-side / "\ No newline" marker
        else:                          # context line (starts with " " or "")
            files.setdefault(current, set()).add(new_ln)
            new_ln += 1
    return files


def snap_line(path: str, line, commentable: dict, tol: int = SNAP_TOL):
    """The commentable line nearest to `line` within tol, or None. Finding
    lines wobble a few lines across runs, so exact misses snap to the
    closest diff line rather than losing the inline placement."""
    lines = commentable.get(path)
    if not lines or not isinstance(line, int):
        return None
    if line in lines:
        return line
    nearest = min(lines, key=lambda x: abs(x - line))
    return nearest if abs(nearest - line) <= tol else None


def _comment_body(f: dict) -> str:
    badge = _SEV_BADGE.get(f.get("severity"), f.get("severity", "?"))
    out = [f"**{badge}** {f.get('issue', '').strip()}"]
    if f.get("verification") == "uncertain":
        out.append("\n> ⚠️ the two verification passes disagreed"
                   + (f" — dissent: {f['dissent_reason']}"
                      if f.get("dissent_reason") else ""))
    suggestion = f.get("suggestion", "").strip()
    if suggestion:
        out.append(f"\n💡 {suggestion}")
    return "\n".join(out)


def build_review_payload(review: dict, diff_text: str,
                         title: str = "Code review") -> dict:
    """The gh api payload for POST /repos/{}/{}/pulls/{n}/reviews: inline
    comments for placeable findings, everything else in the body."""
    commentable = commentable_lines(diff_text)
    comments, unplaced = [], []
    for f in review.get("findings", []):
        line = snap_line(f.get("file", ""), f.get("line"), commentable)
        if line is None:
            unplaced.append(f)
        else:
            comments.append({"path": f["file"], "line": line,
                             "side": "RIGHT", "body": _comment_body(f)})
    body = [f"## 🤖 {title}", "", review.get("summary", "").strip()]
    if review.get("verifier_status") == "failed_open":
        body += ["", "> ⚠️ **Verifier unavailable this run** — findings are "
                     "unfiltered finder output."]
    if not review.get("findings"):
        body += ["", "**No findings survived verification.** ✅"]
    if unplaced:
        body += ["", f"### Findings outside the diff view ({len(unplaced)})",
                 ""]
        for f in unplaced:
            body.append(f"- `{f.get('file', '?')}:{f.get('line', '?')}` "
                        f"{f.get('issue', '').strip()}")
    body += ["", "*Generated by code-review-agent; findings verified by a "
                 "second-pass verifier with repo tools.*"]
    return {"body": "\n".join(body), "event": "COMMENT",
            "comments": comments}


_PR_URL_RE = re.compile(r"^https://github\.com/([^/\s]+)/([^/\s]+)/pull/(\d+)",
                        re.IGNORECASE)


def pr_api_path(pr: str) -> str:
    """REST path of the reviews endpoint for a --pr value.

    `gh pr diff` accepts both a number and a PR URL, but the URL cannot be
    embedded in the API path verbatim. A number keeps the {owner}/{repo}
    placeholder form (resolved from the cwd remote, as before); a URL pins
    owner/repo explicitly -- the cwd remote may point at a different repo
    than the URL, and the placeholder form would silently post to the wrong
    PR of the same number. Anything else raises ValueError."""
    pr = str(pr).strip().rstrip("/")
    if pr.isdigit():
        return f"repos/{{owner}}/{{repo}}/pulls/{pr}/reviews"
    m = _PR_URL_RE.match(pr)
    if m:
        owner, repo, number = m.groups()
        return f"repos/{owner}/{repo}/pulls/{number}/reviews"
    raise ValueError(f"--post needs a PR number or a github.com PR URL; "
                     f"cannot derive one from {pr!r}")


def gh_post_command(pr: str, payload: dict) -> list[str]:
    """argv for posting the payload via gh. The payload itself travels on
    stdin (--input -)."""
    return ["gh", "api", pr_api_path(pr),
            "--method", "POST", "--input", "-"]


def format_dry_run(pr: str, payload: dict) -> str:
    cmd = " ".join(gh_post_command(pr, payload))
    return (f"[dry-run] would run: {cmd}\n"
            f"[dry-run] stdin payload ({len(payload['comments'])} inline "
            "comment(s)):\n"
            + json.dumps(payload, indent=2, ensure_ascii=False))
